// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-m3SzVojE8KUmwQoqhk9mPFEbQJ1ty8',
    appId: '1:623797177770:web:58d0c200e5340557cb2fd3',
    messagingSenderId: '623797177770',
    projectId: 'nikki-next',
    authDomain: 'nikki-next.firebaseapp.com',
    storageBucket: 'nikki-next.firebasestorage.app',
    measurementId: 'G-ENWBH7X3C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBszVIDzf_vd2IB6DhHmdr-VI-H33Ions8',
    appId: '1:623797177770:android:afcb11e66000dd1ecb2fd3',
    messagingSenderId: '623797177770',
    projectId: 'nikki-next',
    storageBucket: 'nikki-next.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7wCfaqmDmrjV-SWgN9pksUHBHeZ_ik3s',
    appId: '1:623797177770:ios:34016d5f71c8a4bccb2fd3',
    messagingSenderId: '623797177770',
    projectId: 'nikki-next',
    storageBucket: 'nikki-next.firebasestorage.app',
    iosBundleId: 'com.example.nikkinext',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7wCfaqmDmrjV-SWgN9pksUHBHeZ_ik3s',
    appId: '1:623797177770:ios:34016d5f71c8a4bccb2fd3',
    messagingSenderId: '623797177770',
    projectId: 'nikki-next',
    storageBucket: 'nikki-next.firebasestorage.app',
    iosBundleId: 'com.example.nikkinext',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH-m3SzVojE8KUmwQoqhk9mPFEbQJ1ty8',
    appId: '1:623797177770:web:5a85108c7f89cb36cb2fd3',
    messagingSenderId: '623797177770',
    projectId: 'nikki-next',
    authDomain: 'nikki-next.firebaseapp.com',
    storageBucket: 'nikki-next.firebasestorage.app',
    measurementId: 'G-EEGCK03FW4',
  );
}
